---
- hosts: localhost
  gather_facts: no
  vars:
    death: no
    hit: no
    testing: no
    debug: no
    maxrooms: 20
    commands: ['move', 'shoot']
    cave_type: 'dodecahedron'
  tasks:
    - name: Initialize the game.
      include_tasks: init.yml

    - include_tasks: wumpus-tasks.yml
