---
- hosts: localhost
  gather_facts: no
  vars:
    death: no
    hit: no
    testing: no
    commands: ['move', 'shoot']
    cave_type: 'dodecahedron'
  tasks:
    - name: Initialize the game.
      include_tasks: init.yml
      when: cave is not defined or arrows is not defined

    - name: Pick random starting position.
      set_fact:
        position: "{{ range(1, 20) | random }}"

    - include_tasks: wumpus-tasks.yml
