---
- hosts: localhost
  gather_facts: no
  connection: local
  vars:
    death: no
    bats_msg: ""
    pit_msg: ""
    wumpus_msg: ""
    commands: ['move', 'shoot']
    cave:
      "1":
        connect: ["2", "5", "8"]
        bats: false
        pit: false
        wumpus: false
      "2":
        connect: ["1", "3", "10"]
        bats: false
        pit: false
        wumpus: false
      "3":
        connect: ["2", "4", "12"]
        bats: false
        pit: false
        wumpus: false
      "4":
        connect: ["3", "5", "14"]
        bats: false
        pit: false
        wumpus: false
      "5":
        connect: ["1", "4", "6"]
        bats: false
        pit: false
        wumpus: false
      "6":
        connect: ["5", "7", "15"]
        bats: false
        pit: false
        wumpus: false
      "7":
        connect: ["6", "8", "17"]
        bats: false
        pit: false
        wumpus: false
      "8":
        connect: ["1", "7", "9"]
        bats: false
        pit: true
        wumpus: false
      "9":
        connect: ["8", "10", "18"]
        bats: false
        pit: false
        wumpus: false
      "10":
        connect: ["2", "9", "11"]
        bats: false
        pit: false
        wumpus: false
      "11":
        connect: ["10", "12", "19"]
        bats: true
        pit: false
        wumpus: false
      "12":
        connect: ["3", "11", "13"]
        bats: false
        pit: false
        wumpus: false
      "13":
        connect: ["12", "14", "20"]
        bats: false
        pit: false
        wumpus: true
      "14":
        connect: ["4", "13", "15"]
        bats: false
        pit: false
        wumpus: false
      "15":
        connect: ["6", "14", "16"]
        bats: false
        pit: true
        wumpus: false
      "16":
        connect: ["15", "17", "20"]
        bats: false
        pit: false
        wumpus: false
      "17":
        connect: ["7", "16", "18"]
        bats: true
        pit: false
        wumpus: false
      "18":
        connect: ["9", "17", "19"]
        bats: false
        pit: false
        wumpus: false
      "19":
        connect: ["11", "18", "20"]
        bats: false
        pit: false
        wumpus: false
      "20":
        connect: ["13", "16", "19"]
        bats: false
        pit: false
        wumpus: false
  tasks:
    - name: Generate the Cave's rooms.
      include_tasks: cave-gen.yml
      when: cave is not defined

    - name: Set initial number of arrows.
      set_fact:
        arrows: 5
        cacheable: yes
      when: arrows is not defined

    - name: Verify input - command.
      assert:
        that:
          - command in commands
        fail_msg: "Accepted commands are 'move' and 'shoot' not '{{ command }}'"
        quiet: yes
      when: command is defined

    - name: Verify input - room.
      assert:
        that:
          - command is defined
          - command == 'move'
          - "room in cave[position]['connect']"
        fail_msg: "*Oof!*  (You hit the wall)"
        quiet: yes
      when: room is defined

    - name: Verify input - rooms.
      assert:
        that:
          - command is defined
          - command == 'shoot'
          - rooms != ''
          - "rooms.split(',')|length <= 4"
        fail_msg: "The arrow falls to the ground at your feet."
        quiet: yes
      when: rooms is defined

    - name: Move to another room.
      set_fact:
        position: "{{ room }}"
        cacheable: yes
      when:
        - command is defined
        - command == 'move'
        - room is defined

    - name: Consume an arrow.
      set_fact:
        arrows: "{{ arrows|int - 1 }}"
        cacheable: yes
      when:
        - command is defined
        - command == 'shoot'
        - rooms is defined

    - name: Arrows
      include_tasks: shoot-arrow.yml
      loop: "{{ rooms.split(',') }}"
      loop_control:
        loop_var: nextroom
      when:
        - command is defined
        - command == 'shoot'
        - rooms is defined

    - name: Check for bats in the room.
      debug:
        msg: |
          *flap*  *flap*  *flap*  (humongous bats pick you up and move you!)
      when:
        - position is defined
        - cave[position]['bats']

    - name: Pick random position.
      set_fact:
        position: "{{ range(1, 20) | random }}"
        cacheable: yes
      when: position is not defined
            or (position is defined and cave[position]['bats'])

    - name: Check for imminent threats.
      set_fact:
        death: yes
      when:
        - position is defined
        - cave[position]['pit'] or cave[position]['wumpus'] or arrows == 0

    - name: Game over by pits.
      debug:
        msg: |
          *AAAUUUUGGGGGHHHHHhhhhhhhhhh...*
          The whistling sound and updraft as you walked into this room of the
          cave apparently weren't enough to clue you in to the presence of the
          bottomless pit. You have a lot of time to reflect on this error as
          you fall many miles to the core of the earth. Look on the bright side;
          you can at least find out if Jules Verne was right...
      when:
        - death
        - cave[position]['pit']

    - name: Game over by evil Wumpus.
      debug:
        msg: |
          *ROAR* *chomp* *snurfle* *chomp*!
          Much to the delight of the Wumpus, you walk right into his mouth,
          making you one of the easiest dinners he's ever had! For you, however,
          it's a rather unpleasant death. The only good thing is that it's been
          so long since the evil Wumpus cleaned his teeth that you immediately
          pass out from the stench!
      when:
        - death
        - cave[position]['wumpus']

    - name: Game over by lack of arrows.
      debug:
        msg: |
          You turn and look at your quiver, and realize with a sinking feeling
          that you've just shot your last arrow (figuratively, too). Sensing this
          with its psychic powers, the evil Wumpus rampages through the cave, finds
          you, and with a mighty *ROAR* eats you alive!
      when:
        - death
        - arrows == 0

    - include_tasks: the-end.yml
      when: death

    - name: Get adjacent rooms.
      set_fact:
        first: "{{ cave[position]['connect'][0] }}"
        second: "{{ cave[position]['connect'][1] }}"
        third: "{{ cave[position]['connect'][2] }}"
      when: not death

    - name: Debug
      include_tasks: debug.yml
      when: not death

    - name: Feel pits.
      set_fact:
        pit_msg: "*whoosh* (I feel a draft from some pits)."
      when: not death
            and (cave[cave[position]['connect'][0]]['pit']
                 or cave[cave[position]['connect'][1]]['pit']
                 or cave[cave[position]['connect'][2]]['pit'])

    - name: Hear bats.
      set_fact:
        bats_msg: "*rustle* *rustle* (must be bats nearby)"
      when: not death
            and (cave[cave[position]['connect'][0]]['bats']
                 or cave[cave[position]['connect'][1]]['bats']
                 or cave[cave[position]['connect'][2]]['bats'])

    - name: Smell Wumpus.
      set_fact:
        wumpus_msg: "*sniff* (I can smell the evil Wumpus nearby!)"
      when: not death
            and (cave[cave[position]['connect'][0]]['wumpus']
                 or cave[cave[position]['connect'][1]]['wumpus']
                 or cave[cave[position]['connect'][2]]['wumpus']
                 or cave[cave[first|string]['connect'][0]]['wumpus']
                 or cave[cave[first|string]['connect'][1]]['wumpus']
                 or cave[cave[first|string]['connect'][2]]['wumpus']
                 or cave[cave[second|string]['connect'][0]]['wumpus']
                 or cave[cave[second|string]['connect'][1]]['wumpus']
                 or cave[cave[second|string]['connect'][2]]['wumpus']
                 or cave[cave[third|string]['connect'][0]]['wumpus']
                 or cave[cave[third|string]['connect'][1]]['wumpus']
                 or cave[cave[third|string]['connect'][2]]['wumpus'])

    - debug:
        msg: |
          You are in room {{ position }} of the cave, and have {{ arrows }} arrows left.
          {{ pit_msg }}
          {{ bats_msg }}
          {{ wumpus_msg }}
          There are tunnels to rooms {{ cave[position]['connect'][0] }}, {{ cave[position]['connect'][1] }}, and {{ cave[position]['connect'][2] }}.
      when: not death

    - debug:
        msg: |
          To play the game you have to run the playbook successively using the
          option --extra-var to define the command variable.
          For example: --extra-var "command=move"
          Possible commands are: move and shoot.
      when:
        - not death
        - command is not defined

    - debug:
        msg: |
          To which room do you wish to move?
          This information should be passed using the option --extra-var to
          define the room variable.
          For example: --extra-var "room=1"
      when:
        - not death
        - command is defined
        - command == 'move'
        - room is not defined

    - debug:
        msg: |
          To which room do you wish to shoot?
          You can specify either a single room or a complete path to a target.
          This information should be passed using the option --extra-var to
          define the rooms variable (note the plural here).
          Shoot in a single room: --extra-var "rooms=2"
          Shoot in a distant room: --extra-var "rooms=1,12"
          In this second example the arrow will try to fly from the current room to room number 1, then the room number 12.
          Up to four rooms can be specified.
      when:
        - not death
        - command is defined
        - command == 'shoot'
        - rooms is not defined
