---
- hosts: localhost
  gather_facts: no
  vars:
    cave_type: 'dodecahedron'
    arrows: 5
  tasks:
    - name: Initialize the game.
      include_tasks: init.yml

    - include_tasks: wumpus-tasks.yml
