---
- name: Bogus moves.
  hosts: all
  become: no
  gather_facts: no
  vars:
    cave:
      "1":
        connect: ["2", "3"]
        pit: false
        wumpus: false
      "2":
        connect: ["1", "3", "4"]
        pit: false
        wumpus: false
      "3":
        connect: ["1", "2", "4"]
        pit: false
        wumpus: false
      "4":
        connect: ["2", "3"]
        pit: false
        wumpus: false
  tasks:
    - name: Initialize important variables.
      set_fact:
        testing: yes

    - name: Teleport to room 1.
      set_fact:
        position: "1"

    - name: Move from room 1 to 4.
      include_tasks: ../../move.yml
      vars:
        room: "4"

    - assert:
        that:
          - position == "1"

    - name: Move to the current room.
      include_tasks: ../../move.yml
      vars:
        room: "1"

    - assert:
        that:
          - position == "1"
