---
- name: Bogus shoot.
  hosts: all
  become: no
  gather_facts: no
  vars:
    death: no
    hit: no
    testing: yes
    cave:
      "1":
        connect: ["2"]
        wumpus: false
      "2":
        connect: ["1"]
        wumpus: false
  tasks:
    - name: Teleport to room 1.
      set_fact:
        position: "1"

    - name: Create one arrow in the quiver.
      set_fact:
        arrows: "1"

    - name: Fail to target a room.
      include_tasks: ../../shoot.yml
      vars:
        rooms: [""]

    - assert:
        that:
          - arrows == "1"
          - not death
          - not hit

    # TODO: Not detected yet. 
    #- block:
    #    - name: Target something that is not a room.
    #      include_tasks: ../../execute-command.yml
    #      vars:
    #        command: 'shoot'
    #        rooms: "wumpus"
    #    - name: The move was incorrectly recognized as valid.
    #      fail:
    #  rescue:
    #    - name: The move was correctly recognized as an error.
    #      assert:
    #        that: yes
