---
- name: Converge
  hosts: all
  become: no
  gather_facts: no

- import_playbook: simple-move.yml
- import_playbook: bogus-move.yml
- import_playbook: sensations.yml
- import_playbook: simple-shoot-1.yml
- import_playbook: simple-shoot-2.yml
- import_playbook: simple-shoot-3.yml
- import_playbook: simple-shoot-4.yml
- import_playbook: simple-shoot-5.yml
- import_playbook: bogus-shoot.yml
- import_playbook: deaths.yml
