---
- name: Simple moves.
  hosts: all
  become: no
  gather_facts: no
  vars:
    arrows: 1
    position: "1"
    cave:
      "1":
        connect: ["2", "3"]
        bats: false
        pit: false
        wumpus: false
      "2":
        connect: ["1", "3"]
        bats: false
        pit: false
        wumpus: false
      "3":
        connect: ["1", "2"]
        bats: false
        pit: false
        wumpus: false
    commands: [ 'move' ]
  tasks:
    - name: Move from room 1 to 2.
      include_tasks: ../../execute-command.yml
      vars:
        command: 'move'
        room: "2"

    - name: Move from room 2 to 3.
      include_tasks: ../../execute-command.yml
      vars:
        command: 'move'
        room: "3"

    - name: Move from room 3 to 1.
      include_tasks: ../../execute-command.yml
      vars:
        command: 'move'
        room: "1"

    - assert:
        that:
          - position == "1"
