---
- name: Simple moves.
  hosts: all
  become: no
  gather_facts: no
  vars:
    testing: yes
    cave:
      "1":
        connect: ["2", "3"]
        pit: no
        wumpus: no
      "2":
        connect: ["1", "3"]
        pit: no
        wumpus: no
      "3":
        connect: ["1", "2"]
        pit: no
        wumpus: no
  tasks:
    - name: Teleport to room 1.
      set_fact:
        position: "1"

    - name: Move from room 1 to 2.
      include_tasks: ../../move.yml
      vars:
        room: "2"

    - name: Move from room 2 to 3.
      include_tasks: ../../move.yml
      vars:
        room: "3"

    - name: Move from room 3 to 1.
      include_tasks: ../../move.yml
      vars:
        room: "1"

    - assert:
        that:
          - position == "1"
