---
- name: Simple shoot - one room.
  hosts: all
  become: no
  gather_facts: no
  vars:
    cave:
      "1":
        connect: ["2"]
        wumpus: false
      "2":
        connect: ["1"]
        wumpus: false
  tasks:
    - name: Initialize important variables.
      set_fact:
        death: no
        hit: no
        testing: yes

    - name: Teleport to room 1.
      set_fact:
        position: "1"

    - name: Create one arrow in the quiver.
      set_fact:
        arrows: "1"

    - name: Shoot from room 1 to 2.
      include_tasks: ../../shoot.yml
      vars:
        rooms: "2"

    - assert:
        that:
          - arrow == "2"
          - arrows == "0"
          - not death
          - not hit
